# Generated by Django 5.0.7 on 2024-07-12 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_is_active_account_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_staff',
        ),
    ]
